routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/{post}', 'WelcomeController@show')->name('blog.show');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blog.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blog.tag');
Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController');
    Route::delete('/trash/{post}', 'PostsController@trash')->name('posts.trash');
    Route::get('/trashed', "PostsController@trashed")->name('posts.trashed');
    Route::put('/restore/{post}', 'PostsController@restore')->name('posts.restore');
    Route::resource('tags', 'TagsController');
});

Route::middleware(['auth', 'admin'])->group(function(){
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use softDeletes;
    protected $dates = ['published_at'];
    protected $fillable = [
        'user_id',
        'title',
        'excerpt',
        'content',
        'image',
        'category_id',
        'published_at'
    ];

    /*
    * RELATIONSHIP FUNCTION
    */
    public function category() {
        return $this->belongsTo(Category::class);
    }

    
    public function tags() {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }

    /*
    * HELPER FUNCTION
    */
    public function deleteImage() {
        Storage::delete($this->image);
    }

    public function hasTag($tag_id) {
        return  in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function scopePublished($query) {
        return $query->where('published_at',"<=", now());
    }

    public function scopeSearch($query) {
        $search = request('search');
        if($search) {
            return $query->where('title', 'like', "%$search%");
        }
        return $query;
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Post;
use Illuminate\Http\Request;
use App\Tag;
use App\User;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'destroy', 'trash');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if(!auth()->user()->isAdmin()){
            $posts = Post::withoutTrashed()->where('user_id', auth()->id())->paginate(10);
        }else{
            $posts = Post::paginate(10);
        }
        
        
        return view('posts.index', compact([
            'posts'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create', compact([
            'categories',
            'tags'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        //Image Upload and stores the name of the image
        $image = $request->file('image')->store('posts');
        // run command: php artisan storage:link
        //Create Post
        $post = Post::create([
            'title'=>$request->title,
            'excerpt'=>$request->excerpt,
            'content'=>$request->content,
            'image'=>$image,
            'user_id'=>auth()->id(),
            'published_at'=>$request->published_at,
            'category_id'=>$request->category_id
        ]);

        $post->tags()->attach($request->tags);
        //session storage
        session()->flash('success', 'Post Created Successfully');
        //redirect
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact(['post', 'categories', 'tags']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = request()->only(['title', 'excerpt', 'content', 'published_at', 'category_id']);
        if($request->hasFile('image')){
            $image = request()->image->store('posts');
            $post->deleteImage();
            $data['image'] = $image;
        }
        $post->update($data);
        
        $post->tags()->sync($request->tags);
        
        session()->flash('success', 'Post Updated Successfully!');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post Deleted Successfully!');
        return redirect()->back();
    }

    public function trash(Post $post){
        $post->delete();
        session()->flash('success', 'Post trashed successfully!');
        return redirect(route('posts.index'));
    }

    public function trashed(){
        $trashed = Post::onlyTrashed()->paginate(10);
        // dd($trashed);
        return view('posts.trashed')->with('posts', $trashed);
    }

    public function restore($id){
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', 'Post restored successfully!');
        return redirect(route('posts.index'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('page-level-scripts')

<!-- JQuery Core
    =====================================-->
<script src="{{asset('assets/js/core/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/core/bootstrap-3.3.7.min.js')}}"></script>

<!-- Magnific Popup
    =====================================-->
<script src="{{asset('assets/js/magnific-popup/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('assets/js/magnific-popup/magnific-popup-zoom-gallery.js')}}"></script>

<!-- JQuery Main
    =====================================-->
<script src="{{asset('assets/js/main/jquery.appear.js')}}"></script>
<script src="{{asset('assets/js/main/isotope.pkgd.min.js')}}"></script>
<script src="{{asset('assets/js/main/parallax.min.js')}}"></script>
<script src="{{asset('assets/js/main/jquery.sticky.js')}}"></script>
<script src="{{asset('assets/js/main/imagesloaded.pkgd.min.js')}}"></script>
<script src="{{asset('assets/js/main/main.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<script>
    console.log('Hello World!');
    
    $("#modalOpener").on("click", "#toggleModal", function () {
        $('#modalOpener').modal('show');
    });

    document.getElementById('title').onkeyup = document.getElementById('title').onkeypress = function () {
        document.getElementById('head').innerHTML = this.value;
    }
 
    document.getElementById('body-content').onkeyup = document.getElementById('body-content').onkeypress = function () {
        document.getElementById('body').innerHTML = this.value;
    }

    var tags = document.getElementById('tags');
    

    var tagSelected = [];
    document.getElementById('tags').onchange = function(){
        tagSelected = [];
        for(i=0; i<tags.length; i++)
        {
            
            if(tags.options[i].selected)
            {
                tagSelected.push(tags.options[i].text);

            }
        }
        console.log(tagSelected);
    document.getElementById('tag').innerHTML = tagSelected;
    }
    
    document.getElementById('imageAdd').onchange = function(){
        console.log(URL.createObjectURL(document.getElementById("imageAdd").files[0]));
        document.getElementById("blogImage").src = URL.createObjectURL(document.getElementById("imageAdd").files[0]);
    }   

</script>

<script>
    flatpickr("#published_at", {
        enableTime: true
    });
    $(document).ready(function () {
        $('.select2').select2();
    });

</script>
@endsection

@section('page-level-styles')
<!-- Favicons -->
<link rel="shortcut icon" href="{{asset('assets/img/favicon.png')}}">
<link rel="apple-touch-icon" href="{{asset('assets/img/apple-touch-icon.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{asset('assets/img/apple-touch-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{asset('assets/img/apple-touch-icon-114x114.png')}}">

<!-- Load Core CSS
    =====================================-->
<link rel="stylesheet" href="{{asset('assets/css/core/animate.min.css')}}">

<!-- Load Main CSS
    =====================================-->
<link rel="stylesheet" href="{{asset('assets/css/main/main.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/main/setting.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/main/hover.css')}}">


<link rel="stylesheet" href="{{asset('assets/css/color/pasific.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/icon/font-awesome.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/icon/et-line-font.css')}}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<div class="card">
    <div class="card-header">Add Post</div>

    <div class="card-body">
        <form action="{{ route('posts.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" id="title"
                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title')}}">

                @if ($errors->has('title'))
                <p class="text-danger font-weight-light">{{$errors->first('title')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="excerpt">Excerpt</label>
                <input type="text" name="excerpt" id="excerpt"
                    class="form-control @error('excerpt') is-invalid @enderror" value="{{ old('excerpt')}}">
                @error('excerpt')
                <p class="text-danger font-weight-light">{{$errors->first('excerpt')}}</p>
                @enderror
            </div>


            <div class="form-group">
                <label for="content">Content</label>
                <input type="hidden" name="content" id="content">
                <trix-editor input="content" id="body-content"></trix-editor>
                @error('content')
                <p class="text-danger font-weight-light">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="category_id"></label>
                <select name="category_id" id="category_id" class="form-control select2">
                    <option value="-1">Select Category</option>
                    @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                @if ($errors->has('category_id'))
                <p class="text-danger font-weight-light">{{$errors->first('category_id')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="tags">Tags</label>
                <select name="tags[]" id="tags" class="form-control select2" multiple>

                    @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                    @endforeach
                </select>
                @if ($errors->has('tags'))
                <p class="text-danger font-weight-light">{{$errors->first('tags')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="date" name="published_at" id="published_at"
                    class="form-control {{ $errors->has('published_at') ? 'is-invalid' : '' }}"
                    value="{{ old('published_at')}}">

                @if ($errors->has('published_at'))
                <p class="text-danger font-weight-light">{{$errors->first('published_at')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="">Image</label>
                
                <input type="file" value="{{ old('image')}}" name="image" id="imageAdd"
                    class="form-control @error('image') is-invalid @enderror">
                @error('image')
                <p class="text-danger font-weight-light">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-success">
            </div>
        </form>
    </div>
</div>

@endsection


@section('preview')
<div class="modal fade" id="toggleModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" >
            <div class="modal-header">
                <h5>Preview!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="row">
                <div class="container">
                    <div class="card">
                        <div class="card-body" id="modal-body">
                            <div class="blog-three-mini" id="data">
                                <h2 class="color-dark" id="head"></h2>
                                <div class="blog-three-attrib">
                                    <div><i class="fa fa-calendar"></i>Live Preview!</div> |
                                    <div><i class="fa fa-pencil"></i><a href="#"></a>{{auth()->user()->name}}</div> |

                                    <div>
                                        Share: <a href="#"><i class="fa fa-facebook-official"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                        <a href="#"><i class="fa fa-pinterest"></i></a>
                                    </div>
                                </div>
                                
                                    <img src="{{asset('storage/posts/default-image.jpg')}}" alt="Blog Image" class="img-responsive" id="blogImage" width="455px" height="300px">
                                
                                <div class="lead mt25" id="body">

                                </div>

                                <div class="blog-post-read-tag mt50">
                                    <i class="fa fa-tags"></i> Tags: <span id="tag" class="font-weight-light"></span>
                                </div>

                            </div>
                            <div class="blog-post-author mb50 pt30 bt-solid-1">
                                <img src="{{\Thomaswelton\LaravelGravatar\Facades\Gravatar::src(auth()->user()->email) }}"
                                    class="img-circle" height="30px" alt="image">
                                <span class="blog-post-author-name">{{auth()->user()->name}}</span> <a
                                    href="https://twitter.com/booisme"><i class="fa fa-twitter"></i></a>
                                <p class="text-weight-light">
                                    @if(auth()->user()->about == null)
                                        N.A.
                                    
                                    @else 
                                            {{auth()->user()->about}}
                                
                                    @endif
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Post</div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                           value="{{ old('title', $post->title) }}"
                           class="form-control @error('title') is-invalid @enderror"
                           name="title" id="title">
                    @error('title')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt"
                              id="excerpt"
                              class="form-control @error('excerpt') is-invalid @enderror"
                              rows="4">{{old('excerpt', $post->excerpt)}}</textarea>
                    @error('excerpt')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <input id="content" type="hidden" name="content" value="{{ old('content', $post->content) }}">
                    <trix-editor input="content"></trix-editor>
                    @error('content')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">Category</label>
                    <select name="category_id" id="category_id" class="form-control select2">
                        <option value="-1" disabled selected>Select...</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}" {{ $post->category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">Tags</label>
                    <select name="tags[]" id="tags" class="form-control select2" multiple>
                        @foreach($tags as $tag)
                            <option value="{{$tag->id}}"
                            {{ old('tags')  ? (in_array($tag->id, old('tags')) ? 'selected': '') : ($post->hasTag($tag->id) ? 'selected' : '') }}
                            >{{ $tag->name }}</option>
                        @endforeach
                    </select>
                    @error('tags')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                           value="{{ $post->published_at }}"
                           class="form-control"
                           name="published_at" id="published_at">
                </div>
                <div class="form-group">
                    <img src="{{ asset('storage/'.$post->image) }}" alt="" width="100%">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                           class="form-control @error('image') is-invalid @enderror"
                           name="image" id="image">
                    @error('image')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Edit Post</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}"  class="btn btn-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header">Posts</div>

        <div class="card-body">
            @if($posts->count() >0)
            <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="128"></td>
                            <td>{{$post->title}}</td>
                            <td>{{$post->excerpt}}</td>
                            {{-- <td>{{$post->category->name}}</td> --}}
                            <td>
                            <a href="{{route('posts.edit', $post->id)}}" class="btn btn-primary btn-sm">Edit</a>
                                
                                <a href="#" class="btn btn-danger btn-sm"
                            onclick="displayModalForm({{$post}})"
                                   data-toggle="modal"
                                   data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @else
                <h5>No Posts</h5>
            @endif
        </div>
    </div>
    <!--DELETE MODAL-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure want to delete Post??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--END DELETE MODAL-->
@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post) {
            var url = '/trash/' + $post.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}"  class="btn btn-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header">Trahed Posts</div>

        <div class="card-body">
            @if($posts->count() >0)
            <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="128"></td>
                            <td>{{$post->title}}</td>
                            <td>{{$post->excerpt}}</td>
                            <td>
                                <form action="{{route('posts.restore', $post->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button href="" class="btn btn-primary btn-sm">Restore</button>
                                </form>
                                
                                <a href="#" class="btn btn-danger btn-sm"
                            onclick="displayModalForm({{$post}})"
                                   data-toggle="modal"
                                   data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <h5>No Trashed Posts</h5>
            @endif
        </div>
    </div>
    <!--DELETE MODAL-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure want to delete Post??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--END DELETE MODAL-->
@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post) {
            var url = '/posts/' + $post.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection